apiVersion: v1
kind: Pod
metadata:
  name: git-sync
  labels:
    app: sidecar
spec:
  containers:
  - name: ctr-web
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/
  - name: ctr-sync               <<==== Start of second container
    image: k8s.gcr.io/git-sync:v3.1.6
    volumeMounts:
    - name: html                 <<==== shared volume
      mountPath: /tmp/git
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/vladimir-cmd/ps-sidecar.git
    - name: GIT_SYNC_BRANCH
      value: master
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_DEST
      value: "html"
  volumes:
  - name: html
    emptyDir: {}